name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello Cory"
          echo "This is another line"
      - name: Print goodbye
        run: echo "Goodbye Cory"
